#ifndef _BASE_ADDR_H_
#define _BASE_ADDR_H_

#define ARM_MUTEXT_MANAGER_BASE
#define ARM_HTDT_BASE
#define ARM_DDR_BASE

#define DMA_LOCAL_MEM_BASE
#define DMA_INST_MEM_BASE
#define DMA_DDR_BASE

#define SCHEDULER_DMA_BASE
#define SCHEDULER_MUTEXT_MANAGER_BASE
#define SCHEDULER_HTDT_BASE
#define SCHEDULER_LOCAL_MEM_BASE
#define SCHEDULER_ID_GENERATOR_BASE

#define SLAVE_LOCAL_MEM_BASE
#define SLAVE_INST_MEM_BASE
#define SLAVE_DDR_BASE


#endif